name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    # - name: Setup NodeJS LTS
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '12.3.1'        
    # - name: Install dependencies
    #   run: npm install monitor     
    # - name: Install angular
    #   run: npm install --no-optional -g @angular/cli  
    - name: Build with Maven
      run: mvn clean install

    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      
      with:
        IMAGE_NAME: 'sombrero'
        TAG: 'latest'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
